import { NivelEducativoId } from '../data/educacion';

export type RootStackParamList = {
  IniciarSesion: undefined;
  Login: undefined;
  CambiarContrasena: undefined;
  SobreNosotros: undefined;
  Contacto: undefined;
  MenuPrincipal: undefined;
  PacienteResumen: undefined;
  ExpedienteGestion: undefined;
  PacienteForm: undefined;
  PacienteEditor: { pacienteId?: number } | undefined;
  ConsultaList: undefined;
  ConsultaForm: { consulta?: { consultaId: number; pacienteId: number; fechaconsulta: string; motivo: string; diagnostico?: string; tratamiento?: string; } } | undefined;
  CitaForm: undefined;
  VacunaForm: undefined;
  MedicacionForm: undefined;
  LesionForm: undefined;
  OperacionForm: undefined;
  CondicionCronicaForm: undefined;
  DocumentoForm: undefined;
  RecordatorioForm: undefined;
  RegistroDentalForm: undefined;
  RecordatorioList: undefined;
  Alergia: undefined;
  Habitos: undefined;
  SeguimientoFisico: undefined;
  Periodo: undefined;
  SaludMental: undefined;
  ExamenClinico: undefined;
  Educacion: undefined;
  EducacionNivel: { nivelId: NivelEducativoId };
  EducacionTema: { nivelId: NivelEducativoId; temaId: string };
  Registro: undefined;
};
